name: Update README # 워크플로우의 이름이다.

on:
  schedule:
    - cron: "0 0 * * *" # 매일 자정에 실행되는 크론 표현식이다.
  push:
    branches:
      - main # main 브랜치에 푸시될 때도 이 워크플로우가 실행된다.

jobs:
  update-readme:
    runs-on: ubuntu-latest # 워크플로우가 Ubuntu 최신 버전에서 실행된다.

    steps:
      - name: Checkout repository # 리포지토리를 체크아웃하는 단계이다.
        uses: actions/checkout@v4 # actions/checkout 액션을 사용한다. 리포지토리의 파일을 가져와 사용할 수 있도록 해준다.

      - name: Set up Node.js # Node.js를 설정하는 단계이다.
        uses: actions/setup-node@v4 # actions/setup-node 액션을 사용한다.
        with:
          node-version: "20" # Node.js 20 버전을 사용한다.

      - name: Install dependencies # 의존성을 설치하는 단계이다.
        run: npm install axios xml2js # axios와 xml2js 패키지를 설치한다.

      - name: Fetch latest blog posts # 최신 블로그 포스트를 가져오는 단계이다.
        run: node fetchPosts.js # fetchPosts.js 스크립트를 실행한다.

      - name: Show changes # 변경된 파일을 보여주는 단계이다.
        run: |
          echo "Changed files:" # 변경된 파일을 출력한다.
          git status # git status 명령어를 실행하여 변경 사항을 표시한다.

      - name: Update README # README를 업데이트하는 단계이다.
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md # README.md 파일을 스테이징한다.
          git commit -m 'Update README with latest blog posts' || echo "No changes to commit" # 커밋을 시도하고, 변경 사항이 없으면 메시지를 출력한다.
          git push # 변경 사항을 푸시한다.
